// Self-hosted motion work, generated by scripts/compress-videos.mjs.
// Sources compressed to web-quality MP4 (720/1080 fit, H.264 + AAC, faststart).
export type Film = {
  slug: string;
  title: string;
  client: string;
  src: string;    // /videos/work/<slug>.mp4
  poster: string; // /videos/work/<slug>.jpg
  w: number;
  h: number;
};

export const films: Film[] = [
  { slug: "sony-massiah", title: "Sony × Massiah", client: "Sony", src: "/videos/work/sony-massiah.mp4", poster: "/videos/work/sony-massiah.jpg", w: 720, h: 1280 },
  { slug: "pkz-sony", title: "PKZ × Sony", client: "PKZ · Sony", src: "/videos/work/pkz-sony.mp4", poster: "/videos/work/pkz-sony.jpg", w: 720, h: 1280 },
  { slug: "porsche", title: "Porsche", client: "Porsche", src: "/videos/work/porsche.mp4", poster: "/videos/work/porsche.jpg", w: 720, h: 1280 },
  { slug: "samsonite", title: "Samsonite", client: "Samsonite", src: "/videos/work/samsonite.mp4", poster: "/videos/work/samsonite.jpg", w: 720, h: 1280 },
  { slug: "samsonite-backpack", title: "Samsonite — Backpack", client: "Samsonite", src: "/videos/work/samsonite-backpack.mp4", poster: "/videos/work/samsonite-backpack.jpg", w: 720, h: 1280 },
  { slug: "sony-roadshow", title: "Sony Roadshow", client: "Sony", src: "/videos/work/sony-roadshow.mp4", poster: "/videos/work/sony-roadshow.jpg", w: 720, h: 1280 },
  { slug: "maxlb-sony", title: "Max LB × Sony", client: "Sony", src: "/videos/work/maxlb-sony.mp4", poster: "/videos/work/maxlb-sony.jpg", w: 720, h: 1280 },
  { slug: "dervis-boxing", title: "Dervis — Boxing", client: "Sport", src: "/videos/work/dervis-boxing.mp4", poster: "/videos/work/dervis-boxing.jpg", w: 1280, h: 720 },
  { slug: "u19-gc", title: "U19 GC", client: "Sport", src: "/videos/work/u19-gc.mp4", poster: "/videos/work/u19-gc.jpg", w: 1280, h: 720 },
  { slug: "royal-family", title: "Royal Family", client: "TBB", src: "/videos/work/royal-family.mp4", poster: "/videos/work/royal-family.jpg", w: 720, h: 1280 },
  { slug: "perspective", title: "Perspective", client: "Short Film", src: "/videos/work/perspective.mp4", poster: "/videos/work/perspective.jpg", w: 720, h: 1280 },
  { slug: "ermi", title: "Ermi", client: "Portrait Film", src: "/videos/work/ermi.mp4", poster: "/videos/work/ermi.jpg", w: 1280, h: 720 },
  { slug: "yuki-studio", title: "Yuki Studio", client: "Studio", src: "/videos/work/yuki-studio.mp4", poster: "/videos/work/yuki-studio.jpg", w: 720, h: 1280 },
  { slug: "vogese-rueche", title: "Vogese Rueche 2026", client: "Campaign", src: "/videos/work/vogese-rueche.mp4", poster: "/videos/work/vogese-rueche.jpg", w: 720, h: 1280 },
  { slug: "smmac-9", title: "SMMAC 9", client: "Event", src: "/videos/work/smmac-9.mp4", poster: "/videos/work/smmac-9.jpg", w: 720, h: 1280 },
  { slug: "bahar-senna", title: "Bahar & Senna", client: "Short Film", src: "/videos/work/bahar-senna.mp4", poster: "/videos/work/bahar-senna.jpg", w: 720, h: 1280 },
  { slug: "sony-roadshow-long", title: "Sony Roadshow — Long Cut", client: "Sony", src: "/videos/work/sony-roadshow-long.mp4", poster: "/videos/work/sony-roadshow-long.jpg", w: 1280, h: 720 },
  { slug: "tetiana-avni", title: "Tetiana & Avni", client: "Wedding Film", src: "/videos/work/tetiana-avni.mp4", poster: "/videos/work/tetiana-avni.jpg", w: 1280, h: 720 },
];
