// Compress his brand/motion videos to web-quality MP4 + a poster frame, and
// generate lib/films.ts. Self-hosted so they play right on the Videos page.
// Idempotent: skips a film whose output .mp4 already exists. Re-run: node scripts/compress-videos.mjs

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "public", "videos", "work");
fs.mkdirSync(OUT, { recursive: true });

const { root, films } = JSON.parse(fs.readFileSync(path.join(__dirname, "films.json"), "utf8"));

function ffprobeDuration(file) {
  const r = spawnSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file], { encoding: "utf8" });
  return parseFloat((r.stdout || "0").trim()) || 0;
}
function ffprobeWH(file) {
  const r = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height", "-of", "csv=s=x:p=0", file], { encoding: "utf8" });
  const [w, h] = (r.stdout || "").trim().split("x").map(Number);
  return { w: w || 1280, h: h || 720 };
}

const SCALE = "scale='min(1280,iw)':'min(1280,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2";
const out = [];

for (const f of films) {
  const src = path.join(root, f.folder, f.file);
  const mp4 = path.join(OUT, `${f.slug}.mp4`);
  const jpg = path.join(OUT, `${f.slug}.jpg`);
  if (!fs.existsSync(src)) { console.warn(`! missing ${f.file}`); continue; }

  if (!fs.existsSync(mp4)) {
    console.log(`> encoding ${f.slug} ...`);
    const enc = spawnSync("ffmpeg", [
      "-y", "-i", src,
      "-vf", SCALE,
      "-c:v", "libx264", "-crf", "25", "-preset", "veryfast",
      "-pix_fmt", "yuv420p", "-movflags", "+faststart",
      "-c:a", "aac", "-b:a", "128k",
      mp4,
    ], { stdio: ["ignore", "ignore", "inherit"] });
    if (enc.status !== 0) { console.warn(`! encode failed ${f.slug}`); continue; }
  } else {
    console.log(`= ${f.slug}.mp4 exists, skip encode`);
  }

  if (!fs.existsSync(jpg)) {
    const t = Math.max(0.5, ffprobeDuration(src) * 0.12);
    spawnSync("ffmpeg", ["-y", "-ss", String(t), "-i", src, "-frames:v", "1", "-vf", SCALE, "-q:v", "3", jpg],
      { stdio: ["ignore", "ignore", "ignore"] });
  }

  const { w, h } = ffprobeWH(mp4);
  const mb = (fs.statSync(mp4).size / 1048576).toFixed(1);
  console.log(`  ${f.slug}: ${w}x${h}  ${mb}MB`);
  out.push({ ...f, src: `/videos/work/${f.slug}.mp4`, poster: `/videos/work/${f.slug}.jpg`, w, h });
}

// ---- generate lib/films.ts ----
let ts = `// Self-hosted motion work, generated by scripts/compress-videos.mjs.
// Sources compressed to web-quality MP4 (720/1080 fit, H.264 + AAC, faststart).
export type Film = {
  slug: string;
  title: string;
  client: string;
  src: string;    // /videos/work/<slug>.mp4
  poster: string; // /videos/work/<slug>.jpg
  w: number;
  h: number;
};

export const films: Film[] = [
`;
for (const f of out) {
  ts += `  { slug: "${f.slug}", title: "${f.title.replace(/"/g, '\\"')}", client: "${f.client.replace(/"/g, '\\"')}", src: "${f.src}", poster: "${f.poster}", w: ${f.w}, h: ${f.h} },\n`;
}
ts += `];\n`;
fs.writeFileSync(path.join(ROOT, "lib", "films.ts"), ts);

const total = out.reduce((a, f) => a + fs.statSync(path.join(OUT, `${f.slug}.mp4`)).size, 0);
console.log(`Done. ${out.length} films, ${(total / 1048576).toFixed(0)}MB total. lib/films.ts written.`);
